"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContainer from "./ThemeContainer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import InputContextProvider from "@/app/context/InputContextProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <InputContextProvider>
        <QueryClientProvider client={queryClient}>
          <ThemeContainer>
            <body className={inter.className}>{children}</body>
          </ThemeContainer>
        </QueryClientProvider>
      </InputContextProvider>
    </html>
  );
}
